@startuml struct

class Project {
    +名称
    +描述
}

class Code {
    +源代码
    +文档
}

class Data {
    +数据集
    +数据处理
}

class ResumeNer
{
    +来自顶级会议
    +简历的NER
}

class ckpts
{
    +模型保存
    +模型复用
}

class HanLPSystem {
    +传统分词器
    +传统NER
}

class hanlp4_5_4{
    +hanlp系统
}

class BertVectorizer {
    +文本向量化
}

class Model {
    +HMM
    +CRF
    +LSTM+HMM
    +LIST+CRF
}

Project --|> Code
Project --|>  Data
Project --|>  HanLPSystem
Code --^  BertVectorizer: 前期处理
Code --|>  Model
Data --|>  ResumeNer
Data --|>  ckpts
Data --|>  hanlp4_5_4
Model --|>  HMM
Model --|>  CRF
Model --|>  LSTM_HMM
Model --|>  LIST_CRF

@enduml
